const icon_paths = {
    "Los Angeles Angels": "angels.gif",
    "Houston Astros": "astros.gif",
    "Oakland Athletics": "athletics.gif",
    "Toronto Blue Jays": "bluejays.gif",
    "Atlanta Braves": "braves.gif",
    "Milwaukee Brewers": "brewers.gif",
    "St. Louis Cardinals": "cardinals.gif",
    "Chicago Cubs": "cubs.gif",
    "Arizona Diamondbacks": "dbacks.gif",
    "Los Angeles Dodgers": "dodgers.gif",
    "San Francisco Giants": "giants.gif",
    "Cleveland Guardians": "guardians.gif",
    "Seatle Mariners": "mariners.gif",
    "Miami Marlins": "marlins.gif",
    "New York Mets": "mets.gif",
    "Washington Nationals": "nationals.gif",
    "Baltimore Orioles": "orioles.gif",
    "San Diego Padres": "padres.gif",
    "Philadelphia Phillies": "phillies.gif",
    "Pittsburgh Pirates": "pirates.gif",
    "Texas Rangers": "rangers.gif",
    "Tampa Bay Rays": "rays.gif",
    "Boston Red Sox": "red-sox.gif",
    "Cincinnati Reds": "reds.gif",
    "Colorado Rockies": "rockies.gif",
    "Kansas City Royals": "royals.gif",
    "Detroit Tigers": "tigers.gif",
    "Minnesota Twins": "twins.gif",
    "Chicago White Sox": "white-sox.gif",
    "New York Yankees": "yankess.gif"
};